#!/bin/sh

# there's run & wait-before-run, we only care about the latter.
COMMANDTYPE=$1

# this is how Steam tries to run the game
if [ "$COMMANDTYPE" == "wait-before-run" ]; then
	# used to decipher which game we'll play
	GAMEBINARY=$(basename "$2")
	# steam game dir
	GAMEDIR=$(dirname "$2")

	PARMARR=( "$@" )
	ARGLEN=${#PARMARR[@]}
	GAMEARGS=${PARMARR[@]:2:$ARGLEN-1}

	if [ "$GAMEBINARY" == "soniccd.exe" ]; then
		cd "$GAMEDIR"
		if ! [ -f ./CD1.3.0.AppImage ]; then
			wget https://github.com/PSebs/Sonic-CD-11-Decompilation/releases/download/1.3.0.2/CD1.3.0.tar.gz
			tar xvfz ./CD1.3.0.tar.gz
			wget https://github.com/PSebs/Sonic-CD-11-Decompilation/releases/download/1.3.0.2/settings.ini
		fi
		./CD1.3.0.AppImage
	fi
fi
